### ISSUE TITLE
Archive Issue

### ISSUE THREAD

**Issue by gray1st** [salesagility/SuiteCRM-Outlook-Plugin#69]
We're trying to use the SuiteCRM plugin for the first time, and receiving a 'get_entry_list' issue when pressing search in Archive.

Debug log at Debug level below

2018-01-15 14:56:49,906 | Background | INFO | Authentication succeeded...
2018-01-15 14:56:49,906 | Background | INFO | Starting normal operations.
2018-01-15 14:56:49,906 | Background | DEBUG | Starting thread Daemon
2018-01-15 14:56:49,923 | Background | DEBUG | Starting thread AS
2018-01-15 14:56:49,923 | Background | DEBUG | Starting thread CS
2018-01-15 14:56:49,923 | Background | DEBUG | Starting thread TS
2018-01-15 14:56:49,923 | AS | DEBUG | AppointmentSyncing.SynchroniseAll not running because not enabled
2018-01-15 14:56:49,923 | Background | DEBUG | Starting thread EM
2018-01-15 14:56:49,923 | TS | DEBUG | TaskSyncing.SynchroniseAll not running because not enabled
2018-01-15 14:56:49,923 | CS | DEBUG | ContactSyncing.SynchroniseAll not running because not enabled
2018-01-15 14:56:49,923 | EM | DEBUG | Auto-Archive iteration started
2018-01-15 14:57:19,930 | 6 | WARN | Anonymous thread 6 running as 'Daemon'.
2018-01-15 14:57:19,930 | 6 | INFO | About to perform FetchEmailCategoriesAction.
2018-01-15 14:57:20,362 | 6 | INFO | FetchEmailCategoriesAction completed:
2018-01-15 14:57:23,286 | EM | DEBUG | Auto-Archive iteration completed
2018-01-15 14:57:28,034 | VSTA_Main | DEBUG | Calling get_available_modules...
2018-01-15 14:57:28,234 | VSTA_Main | DEBUG | Successfully called get_available_modules.
2018-01-15 14:57:30,504 | VSTA_Main | WARN | Tried calling 'get_entry_list' with parameter '{ session = rd1fce9cauu7nc600a8o0n30kf, module_name = Accounts, query = (accounts.name LIKE '%@B.org.uk%') OR (accounts.id in (select eabr.bean_id from email_addr_bean_rel eabr INNER JOIN email_addresses ea on eabr.email_address_id = ea.id where eabr.bean_module = 'Accounts' and ea.email_address LIKE '%@B.org.uk%')), order_by = date_entered DESC, offset = 0, select_fields = System.String[], link_names_to_fields_array = , max_results = 1000, deleted = False }', timeout is 300000ms
2018-01-15 14:57:30,504 | VSTA_Main | ERROR | Failed calling 'get_entry_list'
System.Exception: Failed to parse JSON (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.):

Fatal error: Uncaught ArgumentCountError: Too few arguments to function SugarWebServiceImplv4::get_entry_list(), 8 passed in C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php on line 91 and at least 9 expected in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php:250
Stack trace:
0 C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php(91): SugarWebServiceImplv4->get_entry_list('rd1fce9cauu7nc6...', 'Accounts', '(accounts.name ...', 'date_entered DE...', 0, Array, '1000', false)
1 C:\xampp\htdocs\suitecrm\service\core\SugarRestService.php(133): SugarRestJSON->serve()
2 C:\xampp\htdocs\suitecrm\service\core\webservice.php(66): SugarRestService->serve()
3 C:\xampp\htdocs\suitecrm\service\v4_1\rest.php(53): require_once('C:\xampp\htdocs...')
4 {main}

thrown in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php on line 250

at SuiteCRMClient.CrmRestServer.DeserializeJson[T](String responseJson)
at SuiteCRMClient.CrmRestServer.CheckForCrmError(String jsonResponse)
at SuiteCRMClient.CrmRestServer.GetCrmResponse[T](String strMethod, Object objInput)
Data:System.Collections.ListDictionaryInternal
HResult:-2146233088
2018-01-15 14:57:30,504 | VSTA_Main | ERROR | Failure when custom module included (1)
    Query was '(accounts.name LIKE '%@B.org.uk%') OR (accounts.id in (select eabr.bean_id from email_addr_bean_rel eabr INNER JOIN email_addresses ea on eabr.email_address_id = ea.id where eabr.bean_module = 'Accounts' and ea.email_address LIKE '%@B.org.uk%'))'
System.Exception: Failed to parse JSON (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.):

Fatal error: Uncaught ArgumentCountError: Too few arguments to function SugarWebServiceImplv4::get_entry_list(), 8 passed in C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php on line 91 and at least 9 expected in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php:250
Stack trace:
0 C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php(91): SugarWebServiceImplv4->get_entry_list('rd1fce9cauu7nc6...', 'Accounts', '(accounts.name ...', 'date_entered DE...', 0, Array, '1000', false)
1 C:\xampp\htdocs\suitecrm\service\core\SugarRestService.php(133): SugarRestJSON->serve()
2 C:\xampp\htdocs\suitecrm\service\core\webservice.php(66): SugarRestService->serve()
3 C:\xampp\htdocs\suitecrm\service\v4_1\rest.php(53): require_once('C:\xampp\htdocs...')
4 {main}

thrown in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php on line 250

at SuiteCRMClient.CrmRestServer.DeserializeJson[T](String responseJson)
at SuiteCRMClient.CrmRestServer.CheckForCrmError(String jsonResponse)
at SuiteCRMClient.CrmRestServer.GetCrmResponse[T](String strMethod, Object objInput)
at SuiteCRMClient.RestAPIWrapper.GetEntryList(String module, String query, Int32 limit, String order_by, Int32 offset, Boolean GetDeleted, String[] fields)
at SuiteCRMAddIn.Dialogs.ArchiveDialog.TryQuery(String searchText, String moduleName, List`1 fieldsToSeek)
Data:System.Collections.ListDictionaryInternal
HResult:-2146233088
2018-01-15 14:57:30,819 | VSTA_Main | WARN | Tried calling 'get_entry_list' with parameter '{ session = rd1fce9cauu7nc600a8o0n30kf, module_name = Accounts, query = (accounts.name LIKE '@B.org.uk') OR (accounts.id in (select eabr.bean_id from email_addr_bean_rel eabr INNER JOIN email_addresses ea on eabr.email_address_id = ea.id where eabr.bean_module = 'Accounts' and ea.email_address LIKE '@B.org.uk')), order_by = date_entered DESC, offset = 0, select_fields = System.String[], link_names_to_fields_array = , max_results = 1000, deleted = False }', timeout is 300000ms
2018-01-15 14:57:30,819 | VSTA_Main | ERROR | Failed calling 'get_entry_list'
System.Exception: Failed to parse JSON (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.):

Fatal error: Uncaught ArgumentCountError: Too few arguments to function SugarWebServiceImplv4::get_entry_list(), 8 passed in C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php on line 91 and at least 9 expected in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php:250
Stack trace:
0 C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php(91): SugarWebServiceImplv4->get_entry_list('rd1fce9cauu7nc6...', 'Accounts', '(accounts.name ...', 'date_entered DE...', 0, Array, '1000', false)
1 C:\xampp\htdocs\suitecrm\service\core\SugarRestService.php(133): SugarRestJSON->serve()
2 C:\xampp\htdocs\suitecrm\service\core\webservice.php(66): SugarRestService->serve()
3 C:\xampp\htdocs\suitecrm\service\v4_1\rest.php(53): require_once('C:\xampp\htdocs...')
4 {main}

thrown in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php on line 250

at SuiteCRMClient.CrmRestServer.DeserializeJson[T](String responseJson)
at SuiteCRMClient.CrmRestServer.CheckForCrmError(String jsonResponse)
at SuiteCRMClient.CrmRestServer.GetCrmResponse[T](String strMethod, Object objInput)
Data:System.Collections.ListDictionaryInternal
HResult:-2146233088
2018-01-15 14:57:30,819 | VSTA_Main | ERROR | Failure when custom module included (2)
    Query was '(accounts.name LIKE '@B.org.uk') OR (accounts.id in (select eabr.bean_id from email_addr_bean_rel eabr INNER JOIN email_addresses ea on eabr.email_address_id = ea.id where eabr.bean_module = 'Accounts' and ea.email_address LIKE '@B.org.uk'))'
System.Exception: Failed to parse JSON (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.):

Fatal error: Uncaught ArgumentCountError: Too few arguments to function SugarWebServiceImplv4::get_entry_list(), 8 passed in C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php on line 91 and at least 9 expected in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php:250
Stack trace:
0 C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php(91): SugarWebServiceImplv4->get_entry_list('rd1fce9cauu7nc6...', 'Accounts', '(accounts.name ...', 'date_entered DE...', 0, Array, '1000', false)
1 C:\xampp\htdocs\suitecrm\service\core\SugarRestService.php(133): SugarRestJSON->serve()
2 C:\xampp\htdocs\suitecrm\service\core\webservice.php(66): SugarRestService->serve()
3 C:\xampp\htdocs\suitecrm\service\v4_1\rest.php(53): require_once('C:\xampp\htdocs...')
4 {main}

thrown in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php on line 250

at SuiteCRMClient.CrmRestServer.DeserializeJson[T](String responseJson)
at SuiteCRMClient.CrmRestServer.CheckForCrmError(String jsonResponse)
at SuiteCRMClient.CrmRestServer.GetCrmResponse[T](String strMethod, Object objInput)
at SuiteCRMClient.RestAPIWrapper.GetEntryList(String module, String query, Int32 limit, String order_by, Int32 offset, Boolean GetDeleted, String[] fields)
at SuiteCRMAddIn.Dialogs.ArchiveDialog.TryQuery(String searchText, String moduleName, List`1 fieldsToSeek)
Data:System.Collections.ListDictionaryInternal
HResult:-2146233088
2018-01-15 14:57:30,819 | VSTA_Main | ERROR | Failure when custom module included (3)
System.Exception: Failed to parse JSON (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.):

Fatal error: Uncaught ArgumentCountError: Too few arguments to function SugarWebServiceImplv4::get_entry_list(), 8 passed in C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php on line 91 and at least 9 expected in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php:250
Stack trace:
0 C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php(91): SugarWebServiceImplv4->get_entry_list('rd1fce9cauu7nc6...', 'Accounts', '(accounts.name ...', 'date_entered DE...', 0, Array, '1000', false)
1 C:\xampp\htdocs\suitecrm\service\core\SugarRestService.php(133): SugarRestJSON->serve()
2 C:\xampp\htdocs\suitecrm\service\core\webservice.php(66): SugarRestService->serve()
3 C:\xampp\htdocs\suitecrm\service\v4_1\rest.php(53): require_once('C:\xampp\htdocs...')
4 {main}

thrown in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php on line 250

at SuiteCRMClient.CrmRestServer.DeserializeJson[T](String responseJson)
at SuiteCRMClient.CrmRestServer.CheckForCrmError(String jsonResponse)
at SuiteCRMClient.CrmRestServer.GetCrmResponse[T](String strMethod, Object objInput)
at SuiteCRMClient.RestAPIWrapper.GetEntryList(String module, String query, Int32 limit, String order_by, Int32 offset, Boolean GetDeleted, String[] fields)
at SuiteCRMAddIn.Dialogs.ArchiveDialog.TryQuery(String searchText, String moduleName, List`1 fieldsToSeek)
at SuiteCRMAddIn.Dialogs.ArchiveDialog.Search(String searchText)
Data:System.Collections.ListDictionaryInternal
HResult:-2146233088
2018-01-15 14:57:33,147 | VSTA_Main | WARN | Tried calling 'get_entry_list' with parameter '{ session = rd1fce9cauu7nc600a8o0n30kf, module_name = Contacts, query = (contacts.first_name LIKE '%@B.org.uk%' OR contacts.last_name LIKE '%@B.org.uk%') OR (contacts.id in (select eabr.bean_id from email_addr_bean_rel eabr INNER JOIN email_addresses ea on eabr.email_address_id = ea.id where eabr.bean_module = 'Contacts' and ea.email_address LIKE '%*@B.org.uk%')), order_by = date_entered DESC, offset = 0, select_fields = System.String[], link_names_to_fields_array = , max_results = 1000, deleted = False }', timeout is 300000ms
2018-01-15 14:57:33,148 | VSTA_Main | ERROR | Failed calling 'get_entry_list'
System.Exception: Failed to parse JSON (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.):

Fatal error: Uncaught ArgumentCountError: Too few arguments to function SugarWebServiceImplv4::get_entry_list(), 8 passed in C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php on line 91 and at least 9 expected in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php:250
Stack trace:
0 C:\xampp\htdocs\suitecrm\service\core\REST\SugarRestJSON.php(91): SugarWebServiceImplv4->get_entry_list('rd1fce9cauu7nc6...', 'Contacts', '(contacts.first...', 'date_entered DE...', 0, Array, '1000', false)
1 C:\xampp\htdocs\suitecrm\service\core\SugarRestService.php(133): SugarRestJSON->serve()
2 C:\xampp\htdocs\suitecrm\service\core\webservice.php(66): SugarRestService->serve()
3 C:\xampp\htdocs\suitecrm\service\v4_1\rest.php(53): require_once('C:\xampp\htdocs...')
4 {main}

thrown in C:\xampp\htdocs\suitecrm\service\v4\SugarWebServiceImplv4.php on line 250

at SuiteCRMClient.CrmRestServer.DeserializeJson[T](String responseJson)
at SuiteCRMClient.CrmRestServer.CheckForCrmError(String jsonResponse)
at SuiteCRMClient.CrmRestServer.GetCrmResponse[T](String strMethod, Object objInput)
Data:System.Collections.ListDictionaryInternal
HResult:-2146233088

**Comment by gray1st** [comment]
Plugin version 3.0.9.0

PHP Version 7.2.0

**Comment by simon-brooke** [comment]
Aye, we're investigating a similar (probably related) problem with PHP 7.1 now, this is probably the same thing.

**Comment by gray1st** [comment]
Have just re-installed php to ensure it wasn't something silly with our set-up, but the same issue.

It seems to be expecting 9 parameters into SugarRestJSON.php whereas I believe only 8 are being passed.

**Comment by simon-brooke** [comment]
Yes, that's right. I've fixed it in my current `dev` build, and that bit's working; but we have other bugs so I can't give you a date for next release.

**Comment by cameronblaikie** [comment]
This should be resolved in later version of SuiteCRM and outlook version. Please re-open if still an issue.
